cmake_minimum_required(VERSION 3.5)
project(QImPlotExamples LANGUAGES CXX)
add_subdirectory(qt-with-implots)
add_subdirectory(qimwidget-test)
add_subdirectory(qimfigure-test)
add_subdirectory(qimfigure-line-color-test)
add_subdirectory(qimfigure-marker-annotation-test)
add_subdirectory(qimfigure-bars-style-test)
add_subdirectory(qimfigure-borderless-test)
add_subdirectory(readme-2d-example)
add_subdirectory(readme-3d-example)
